
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TABLE1]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TABLE1](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
DROP PROCEDURE IF EXISTS [dbo].[GET_ITEMS]
GO
create procedure GET_ITEMS
AS
    SELECT ID, NAME FROM TABLE1 


GO
DROP PROCEDURE IF EXISTS [dbo].[NEW_ITEM]
GO
create procedure NEW_ITEM(@NAME NVARCHAR(255))
AS
    INSERT INTO TABLE1 (NAME) VALUES (@NAME)

